### ISSUE TITLE
Use of undeclared identifier 'itoa'

### ISSUE THREAD

**Issue by gnuchanos** [vedangasDARKNINJA/Raylib-Text-Editor#1]
for (int i = 0; i < m_Lines.size(); ++i)
	{
		const char* lineNumber = itoa(i + 1, buffer, 10);
		int width = MeasureText(lineNumber, 20);
		DrawText(lineNumber, 15 - width, 10 + i * 20, 20, GRAY);
	}

what is this

**Comment by vedangjavdekar** [comment]
[itoa](https://cplusplus.com/reference/cstdlib/itoa/) is a cstdlib function that converts number into a string based on the radix provided. It's using that function for converting the index to c string.

Please check if the latest commit bdb8e48 fixes it for you.

Thanks!
